name: Dockerized Quality Gate
on: [push]

# Permissions needed to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # JOB 1: THE BUILDER
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t monitor-app .

  # JOB 2: THE AUDITOR
  audit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Security Scan
        run: |
          pip install bandit
          # Generate report
          bandit -r . -f html -o index.html || true
      - name: Upload for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # This grabs the index.html we just made

  # JOB 3: THE TESTER
  test:
    needs: [build, audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Re-build and Run Tests
        run: |
          docker build -t monitor-app .
          docker run --rm monitor-app pytest test_app.py

  # JOB 4: THE DEPLOYER (The Live Website)
  deploy:
    needs: test # Only deploy the report if the tests pass!
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4




















und

















